/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Nic
 */
public class ViewCLiente extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewCLiente
     */
    public ViewCLiente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        btnPerfilUsuario = new javax.swing.JMenuItem();
        btnPerfilMascota = new javax.swing.JMenuItem();
        btnReservar = new javax.swing.JMenuItem();
        btnMisReservas = new javax.swing.JMenuItem();
        btnServiciosDisponibles = new javax.swing.JMenuItem();
        BtnHistorial = new javax.swing.JMenuItem();
        btnFacturacuin = new javax.swing.JMenuItem();
        btnCerrar = new javax.swing.JMenuItem();
        btnNoti = new javax.swing.JMenu();
        btnPersona = new javax.swing.JMenu();
        btnPerro = new javax.swing.JMenu();

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Menu(1).png"))); // NOI18N

        btnPerfilUsuario.setText("Perfil Usuario");
        btnPerfilUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilUsuarioActionPerformed(evt);
            }
        });
        jMenu3.add(btnPerfilUsuario);

        btnPerfilMascota.setText("Perfil de Mascota");
        btnPerfilMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilMascotaActionPerformed(evt);
            }
        });
        jMenu3.add(btnPerfilMascota);

        btnReservar.setText("Reservar Servicios");
        btnReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarActionPerformed(evt);
            }
        });
        jMenu3.add(btnReservar);

        btnMisReservas.setText("Mis Reservas");
        btnMisReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMisReservasActionPerformed(evt);
            }
        });
        jMenu3.add(btnMisReservas);

        btnServiciosDisponibles.setText("Servicios Disponibles");
        btnServiciosDisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServiciosDisponiblesActionPerformed(evt);
            }
        });
        jMenu3.add(btnServiciosDisponibles);

        BtnHistorial.setText("Historial de Servicios");
        BtnHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHistorialActionPerformed(evt);
            }
        });
        jMenu3.add(BtnHistorial);

        btnFacturacuin.setText("Facturacion y Pagos");
        btnFacturacuin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturacuinActionPerformed(evt);
            }
        });
        jMenu3.add(btnFacturacuin);

        btnCerrar.setText("Cerrar Sesion");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jMenu3.add(btnCerrar);

        jMenuBar2.add(jMenu3);

        btnNoti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/IconNotif_1.png"))); // NOI18N
        btnNoti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNotiMouseClicked(evt);
            }
        });
        jMenuBar2.add(btnNoti);

        btnPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/IconPersona_1.png"))); // NOI18N
        btnPersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPersonaMouseClicked(evt);
            }
        });
        jMenuBar2.add(btnPersona);

        btnPerro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/PerroC(1).png"))); // NOI18N
        btnPerro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPerroMouseClicked(evt);
            }
        });
        jMenuBar2.add(btnPerro);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 616, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPerroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerroMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPerroMouseClicked

    private void btnPersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPersonaMouseClicked

    private void btnNotiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNotiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNotiMouseClicked

    private void btnPerfilUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPerfilUsuarioActionPerformed

    private void BtnHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHistorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnHistorialActionPerformed

    private void btnFacturacuinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturacuinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFacturacuinActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnServiciosDisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServiciosDisponiblesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnServiciosDisponiblesActionPerformed

    private void btnMisReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMisReservasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMisReservasActionPerformed

    private void btnReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReservarActionPerformed

    private void btnPerfilMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilMascotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPerfilMascotaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem BtnHistorial;
    public javax.swing.JMenuItem btnCerrar;
    public javax.swing.JMenuItem btnFacturacuin;
    public javax.swing.JMenuItem btnMisReservas;
    public javax.swing.JMenu btnNoti;
    public javax.swing.JMenuItem btnPerfilMascota;
    public javax.swing.JMenuItem btnPerfilUsuario;
    public javax.swing.JMenu btnPerro;
    public javax.swing.JMenu btnPersona;
    public javax.swing.JMenuItem btnReservar;
    public javax.swing.JMenuItem btnServiciosDisponibles;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar2;
    // End of variables declaration//GEN-END:variables
}
